---
services:
  ts-overseerr:
    image: tailscale/tailscale:latest
    container_name: ts-overseerr
    hostname: ${TS_HOSTNAME}
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TS_AUTHKEY=${TS_AUTHKEY}
      - "TS_EXTRA_ARGS=--advertise-tags=tag:container --reset"
      - TS_SERVE_CONFIG=/config/overseerr.json
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_USERSPACE=false
    volumes:
      - ${PWD}/state:/var/lib/tailscale
      - ${PWD}/config:/config
    devices:
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - net_admin
    restart: unless-stopped

  overseerr:
    image: lscr.io/linuxserver/overseerr:latest
    container_name: overseerr
    network_mode: service:ts-overseerr
    depends_on:
      - ts-overseerr
    volumes:
      - overseerr-data:/app/config
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - LOG_LEVEL=info
      - TZ=TZ=America/Toronto
    restart: unless-stopped

volumes:
  overseerr-data:
    driver: local
  ts-overseerr:
    driver: local
