services:
  overseerr:
    image: lscr.io/linuxserver/overseerr:latest
    container_name: overseerr
    network_mode: "service:tailscale-request"  # Use Tailscale's network
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=America/Toronto
    volumes:
      - ${DOCKER_VOLUME_BASE}/overseerr:/config
    restart: unless-stopped

  tailscale-request:
    image: tailscale/tailscale:latest
    container_name: tailscale-request
    hostname: request-stack
    environment:
      - TS_AUTHKEY=${TS_AUTHKEY}
      - TS_EXTRA_ARGS=--advertise-tags=tag:container
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_USERSPACE=false
    volumes:
      - ${DOCKER_VOLUME_BASE}/tailscale:/var/lib/tailscale
    devices:
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
